global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using $safeprojectname$.Common.Abstract;
global using $safeprojectname$.Common.Extensions;
global using Domain.Common.ValueObjects;
global using FluentValidation;
global using MediatR;
